spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbstudent
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#  在控制台显示数据表
    show-sql: true